import { ChangeEvent, useEffect, useState } from "react";
import { CalendarBlank, CoatHanger, Plus, Sparkle, UserCircle, ArrowRight, Camera, Image as ImageIcon, Archive, Trash, ArrowCounterClockwise } from "@phosphor-icons/react";
import { applyDocumentLocale, copy, type Locale } from "./locales";
import { createItem, loadPrototypeData, resetPrototypeData, resolveDuplicate, savePrototypeData, type PrototypeData, type WardrobeItem } from "./prototype-data";
import { Card, EmptyState, PageHeader, PrimaryButton, SecondaryButton } from "./ui";

type Destination = "today" | "wardrobe" | "add" | "outfits" | "profile";
type Draft = Omit<WardrobeItem, "id" | "createdAt" | "archived">;
const destinations: Destination[] = ["today", "wardrobe", "add", "outfits", "profile"];
const navIcons = { today: CalendarBlank, wardrobe: CoatHanger, add: Plus, outfits: Sparkle, profile: UserCircle };
const blankDraft = (): Draft => ({ name: "", category: "חולצה", color: "", season: "כל השנה", style: "", quantity: 1 });
const he = (locale: Locale, hebrew: string, english: string) => locale === "he-IL" ? hebrew : english;

function LanguageSwitcher({ locale, setLocale }: { locale: Locale; setLocale: (v: Locale) => void }) { return <label className="language-switcher"><span>{copy[locale].switchLanguage}</span><select value={locale} onChange={(e) => setLocale(e.target.value as Locale)}><option value="he-IL">עברית</option><option value="en">English</option></select></label>; }
function BottomNavigation({ active, locale, onSelect }: { active: Destination; locale: Locale; onSelect: (d: Destination) => void }) { return <nav className="bottom-nav" aria-label={he(locale, "ניווט ראשי", "Primary navigation")}>{destinations.map((destination) => { const Icon = navIcons[destination]; return <button key={destination} className={`bottom-nav__item ${active === destination ? "is-active" : ""} ${destination === "add" ? "bottom-nav__item--add" : ""}`} type="button" aria-current={active === destination ? "page" : undefined} onClick={() => onSelect(destination)}><Icon aria-hidden="true" weight={destination === "add" ? "bold" : "regular"}/><span>{copy[locale].nav[destination]}</span></button>; })}</nav>; }

function Onboarding({ data, update }: { data: PrototypeData; update: (next: PrototypeData) => void }) {
  const steps = [
    ["ברוכים הבאים לארון שלך", "נבנה יחד ארון דיגיטלי פשוט, פריט אחד בכל פעם.", "welcome"], ["איך נוח לך לראות לוקים?", "נציג לוקים על קולב, שטוח או כהשראה בלבד.", "presentation"], ["מה הגובה וטווח הגיל שלך?", "אפשר לדלג — הנתונים אופציונליים.", "details"], ["מה חשוב לך מהארון?", "למשל: להתלבש מהר, לגלות שילובים או לצמצם קניות.", "goals"], ["איזה סגנון מרגיש לך נכון?", "אפשר לבחור יותר מתשובה אחת.", "style"], ["הארון גדל בהדרגה", "אין צורך להוסיף הכול היום. כל פריט שתאשרו יצטרף לארון המקומי שלכם.", "growth"], ["איך נתחיל?", "תמיד אפשר להוסיף עוד אחר כך.", "start"]
  ]; const [step, setStep] = useState(data.onboarding.step); const [value, setValue] = useState(""); const current = steps[step];
  const persist = (complete = false) => update({ ...data, onboarding: { step, complete, answers: { ...data.onboarding.answers, [current[2]]: value } } });
  const next = () => { const final = step === steps.length - 1; persist(final); if (!final) setStep(step + 1); };
  return <main className="onboarding"><div className="onboarding__progress" aria-label={`שלב ${step + 1} מתוך ${steps.length}`}><span style={{ width: `${((step + 1) / steps.length) * 100}%` }}/></div><p className="eyebrow">שלב {step + 1} מתוך {steps.length}</p><h1>{current[0]}</h1><p>{current[1]}</p>{["presentation", "goals", "style"].includes(current[2]) && <div className="choice-list">{(current[2] === "presentation" ? ["על קולב", "לוק שטוח", "השראה מצולמת"] : current[2] === "goals" ? ["להתלבש מהר", "לגלות שילובים", "לנצל מה שכבר יש"] : ["קלאסי", "נינוח", "נועז"]).map((option) => <button type="button" className={value === option ? "choice is-selected" : "choice"} onClick={() => setValue(option)} key={option}>{option}</button>)}</div>}{current[2] === "details" && <input className="text-input" value={value} onChange={(e) => setValue(e.target.value)} placeholder="גובה / טווח גיל (אופציונלי)" />}{current[2] === "start" && <div className="choice-list">{["צלמו את הלוק של היום", "בחרו תמונות", "הוסיפו פריט ידנית", "דלגו לעת עתה"].map((option) => <button type="button" className={value === option ? "choice is-selected" : "choice"} onClick={() => setValue(option)} key={option}>{option}</button>)}</div>}<div className="onboarding__actions">{step > 0 && <SecondaryButton onClick={() => { persist(); setStep(step - 1); }}>חזרה</SecondaryButton>}<PrimaryButton onClick={next}>{step === steps.length - 1 ? "סיום" : "המשך"}<ArrowRight weight="bold"/></PrimaryButton>{["details", "growth"].includes(current[2]) && <button type="button" className="link-button" onClick={next}>דלגו</button>}</div></main>;
}

function ItemForm({ initial, onSave, onCancel }: { initial?: WardrobeItem; onSave: (d: Draft) => void; onCancel: () => void }) { const [draft, setDraft] = useState<Draft>(initial ? { name: initial.name, category: initial.category, color: initial.color, season: initial.season, style: initial.style, quantity: initial.quantity, image: initial.image } : blankDraft()); const image = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) { const reader = new FileReader(); reader.onload = () => setDraft((d) => ({ ...d, image: String(reader.result) })); reader.readAsDataURL(file); } }; return <form className="item-form" onSubmit={(e) => { e.preventDefault(); onSave(draft); }}><label>תמונה<input accept="image/*" capture="environment" type="file" onChange={image}/></label>{draft.image && <img className="image-preview" src={draft.image} alt="תצוגה מקדימה"/>}<label>שם הפריט<input required value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })}/></label><label>קטגוריה<select value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })}>{["חולצה", "מכנסיים", "שמלה", "ז׳קט", "נעליים", "אביזר"].map((x) => <option key={x}>{x}</option>)}</select></label><label>צבע<input value={draft.color} onChange={(e) => setDraft({ ...draft, color: e.target.value })} placeholder="למשל: כחול"/></label><label>עונה<input value={draft.season} onChange={(e) => setDraft({ ...draft, season: e.target.value })}/></label><label>סגנון<input value={draft.style} onChange={(e) => setDraft({ ...draft, style: e.target.value })}/></label><label>כמות<input type="number" min="1" value={draft.quantity} onChange={(e) => setDraft({ ...draft, quantity: Number(e.target.value) })}/></label><div className="form-actions"><SecondaryButton onClick={onCancel}>ביטול</SecondaryButton><PrimaryButton type="submit">שמירה</PrimaryButton></div></form>; }

function Today({ locale, items, go }: { locale: Locale; items: WardrobeItem[]; go: (d: Destination) => void }) { const recent = items.filter((item) => !item.archived).slice(-3).reverse(); if (!recent.length) return <main className="page"><PageHeader eyebrow={he(locale, "הארון שלך, בקצב שלך", "Your wardrobe, at your pace")} title={he(locale, "לא צריך לצלם את כל הארון היום.", "No need to photograph everything today.")}/><Card className="today-hero"><EmptyState title={he(locale, "מתחילים מפריט אחד", "Start with one item")} body={he(locale, "הארון גדל בהדרגה. אפשר להתחיל מלוק של היום או מפריט אחד.", "Your wardrobe grows gradually. Start with today's look or one item.")}><PrimaryButton onClick={() => go("add")}>צלמו את הלוק של היום</PrimaryButton><SecondaryButton onClick={() => go("add")}>הוסיפו פריט</SecondaryButton></EmptyState></Card></main>; return <main className="page"><PageHeader eyebrow={he(locale, "היום", "Today")} title={he(locale, `יש בארון ${items.filter((x) => !x.archived).length} פריטים`, `${items.filter((x) => !x.archived).length} wardrobe items`)}/><Card className="weather-card"><span>☼</span><div><p className="eyebrow">תצוגה מקדימה</p><h2>לוק מותאם למזג האוויר</h2><p>הצעה מקומית לדוגמה — לא המלצה חכמה בזמן אמת.</p></div></Card><h2 className="section-title">נוספו לאחרונה</h2><ItemGrid items={recent} open={() => go("wardrobe")}/><PrimaryButton onClick={() => go("outfits")}>לצפייה בלוקים</PrimaryButton></main>; }
function ItemGrid({ items, open }: { items: WardrobeItem[]; open: (i: WardrobeItem) => void }) { return <div className="item-grid">{items.map((item) => <button type="button" className="item-tile" onClick={() => open(item)} key={item.id}>{item.image ? <img src={item.image} alt=""/> : <span className="item-tile__placeholder">{item.category}</span>}<strong>{item.name}</strong><small>{item.color || item.category} · {item.quantity}</small></button>)}</div>; }

function Wardrobe({ data, update }: { data: PrototypeData; update: (d: PrototypeData) => void }) { const [selected, setSelected] = useState<WardrobeItem | null>(null); const [adding, setAdding] = useState(false); const active = data.items.filter((x) => !x.archived); const save = (draft: Draft) => { update({ ...data, items: selected ? data.items.map((x) => x.id === selected.id ? { ...x, ...draft } : x) : [...data.items, createItem(draft)] }); setSelected(null); setAdding(false); }; if (adding || selected) return <main className="page"><PageHeader title={selected ? "עריכת פריט" : "הוספת פריט ידנית"}/><ItemForm initial={selected || undefined} onSave={save} onCancel={() => { setSelected(null); setAdding(false); }}/>{selected && <div className="danger-actions"><SecondaryButton onClick={() => update({ ...data, items: data.items.map((x) => x.id === selected.id ? { ...x, archived: !x.archived } : x) })}>{selected.archived ? <><ArrowCounterClockwise/>שחזור</> : <><Archive/>ארכוב</>}</SecondaryButton><SecondaryButton onClick={() => { if (confirm("למחוק את הפריט לצמיתות?")) { update({ ...data, items: data.items.filter((x) => x.id !== selected.id) }); setSelected(null); } }}><Trash/>מחיקה</SecondaryButton></div>}</main>; return <main className="page"><PageHeader eyebrow="הארון" title="הפריטים שלך"><PrimaryButton onClick={() => setAdding(true)}><Plus/>הוספת פריט</PrimaryButton></PageHeader>{active.length ? <ItemGrid items={active} open={setSelected}/> : <Card><EmptyState title="הארון עדיין ריק" body="הוסיפו פריט ידנית או בחרו תמונה. כל הנתונים נשמרים בדפדפן הזה בלבד."><PrimaryButton onClick={() => setAdding(true)}>הוספת פריט ידנית</PrimaryButton></EmptyState></Card>}<details className="archive-list"><summary>פריטים בארכיון ({data.items.length - active.length})</summary>{data.items.filter((x) => x.archived).map((item) => <button type="button" onClick={() => setSelected(item)} key={item.id}>{item.name}</button>)}</details></main>; }

function Add({ data, update, go }: { data: PrototypeData; update: (d: PrototypeData) => void; go: (d: Destination) => void }) { const [image, setImage] = useState<string>(); const [review, setReview] = useState(false); const [candidate, setCandidate] = useState<Draft>({ ...blankDraft(), name: "פריט שזוהה לדוגמה", color: "כחול" }); const [duplicate, setDuplicate] = useState(false); const match = data.items.find((x) => !x.archived); const file = (e: ChangeEvent<HTMLInputElement>) => { const item = e.target.files?.[0]; if (item) { const reader = new FileReader(); reader.onload = () => { setImage(String(reader.result)); setCandidate((x) => ({ ...x, image: String(reader.result) })); setReview(true); }; reader.readAsDataURL(item); } }; const approve = () => match ? setDuplicate(true) : (update({ ...data, items: [...data.items, createItem(candidate)] }), go("wardrobe")); if (duplicate && match) return <main className="page"><PageHeader title="בדיקת כפילות מדומה"/><Card><p className="prototype-note">לוגיקת אבטיפוס בלבד — לא בוצע ניתוח דמיון אמיתי.</p><div className="duplicate-pair"><span>{candidate.name}</span><span>{match.name}</span></div>{[["same", "זה אותו פריט שכבר קיים"], ["additional", "יש לי פריט נוסף שנראה זהה"], ["different", "זה פריט אחר"]].map(([decision, label]) => <PrimaryButton key={decision} onClick={() => { update({ ...data, items: resolveDuplicate(data.items, createItem(candidate), decision as "same" | "additional" | "different", match.id) }); go("wardrobe"); }}>{label}</PrimaryButton>)}</Card></main>; if (review) return <main className="page"><PageHeader title="בדיקת זיהוי מדומה"/><Card><p className="prototype-note">זוהי הצעה מדומה. לא הופעל AI ולא ייכנס פריט לארון עד לאישור.</p>{image && <img className="image-preview" src={image} alt="התמונה שנבחרה"/>}<ItemForm initial={{ ...createItem(candidate) }} onSave={(draft) => setCandidate(draft)} onCancel={() => setReview(false)}/><div className="form-actions"><SecondaryButton onClick={() => setReview(false)}>דחייה</SecondaryButton><PrimaryButton onClick={approve}>אישור הפריט</PrimaryButton></div></Card></main>; return <main className="page"><PageHeader title="הוספה"/><div className="add-options">{[[Camera, "הלוק של היום"], [CoatHanger, "פריט לבוש יחיד"], [Sparkle, "כמה פריטים בתמונה"], [ImageIcon, "בחירה מהגלריה"]].map(([Icon, label]) => <label className="add-option" key={String(label)}><Icon/><span>{label as string}</span><input type="file" accept="image/*" capture={label === "הלוק של היום" ? "environment" : undefined} onChange={file}/></label>)}</div><SecondaryButton onClick={() => go("wardrobe")}>הוספת פריט ידנית</SecondaryButton></main>; }

function Outfits({ data, update }: { data: PrototypeData; update: (d: PrototypeData) => void }) { const items = data.items.filter((x) => !x.archived); if (items.length < 2) return <main className="page"><PageHeader title="לוקים"/><Card><EmptyState title="כדאי להוסיף עוד פריטים" body="כשיהיו לפחות שני פריטים, נציג כאן שילובים מקומיים לדוגמה."/></Card></main>; return <main className="page"><PageHeader title="לוקים לדוגמה"/><p className="prototype-note">הצעות אבטיפוס פשוטות, לא מנוע התאמה חכם.</p>{[0, 1].map((n) => { const id = `outfit-${n}`; const favorite = data.favorites.includes(id); return <Card className="outfit-card" key={id}><div>{items.slice(n, n + 2).map((x) => <span key={x.id}>{x.name}</span>)}</div><SecondaryButton onClick={() => update({ ...data, favorites: favorite ? data.favorites.filter((x) => x !== id) : [...data.favorites, id] })}>♥ {favorite ? "נשמר" : "שמירה"}</SecondaryButton></Card>; })}</main>; }
function Profile({ data, update, locale, setLocale, restart }: { data: PrototypeData; update: (d: PrototypeData) => void; locale: Locale; setLocale: (l: Locale) => void; restart: () => void }) { return <main className="page"><PageHeader title="פרופיל"/><Card className="profile-card"><LanguageSwitcher locale={locale} setLocale={setLocale}/><h2>התשובות שלך</h2><pre>{JSON.stringify(data.onboarding.answers, null, 2)}</pre><SecondaryButton onClick={restart}>התחלה מחדש של ההיכרות</SecondaryButton></Card><Card className="profile-card"><h2>פרטיות האבטיפוס</h2><p>בשלב זה הנתונים נשמרים בדפדפן הזה בלבד באמצעות localStorage. אין חשבון, ענן או שיתוף נתונים.</p><SecondaryButton onClick={() => { if (confirm("למחוק את כל נתוני האבטיפוס?")) { resetPrototypeData(); update(loadPrototypeData()); } }}>איפוס כל נתוני האבטיפוס</SecondaryButton></Card></main>; }

export function AppShell() { const [data, setData] = useState<PrototypeData>(() => loadPrototypeData()); const [locale, setLocale] = useState<Locale>(() => (localStorage.getItem("wardrobe-locale") as Locale) || "he-IL"); const [active, setActive] = useState<Destination>("today"); useEffect(() => { applyDocumentLocale(locale); localStorage.setItem("wardrobe-locale", locale); }, [locale]); const update = (next: PrototypeData) => { setData(next); savePrototypeData(next); }; if (!data.onboarding.complete) return <div className="app-shell"><Onboarding data={data} update={update}/></div>; const props = { data, update }; const content = active === "today" ? <Today locale={locale} items={data.items} go={setActive}/> : active === "wardrobe" ? <Wardrobe {...props}/> : active === "add" ? <Add {...props} go={setActive}/> : active === "outfits" ? <Outfits {...props}/> : <Profile {...props} locale={locale} setLocale={setLocale} restart={() => update({ ...data, onboarding: { ...data.onboarding, complete: false, step: 0 } })}/>; return <div className="app-shell"><div className="app-shell__top"><LanguageSwitcher locale={locale} setLocale={setLocale}/></div>{content}<BottomNavigation active={active} locale={locale} onSelect={setActive}/></div>; }
