import { ChangeEvent, useEffect, useState } from "react";
import { CalendarBlank, CoatHanger, Plus, Sparkle, UserCircle, ArrowRight, Camera, Image as ImageIcon, Archive, Trash, ArrowCounterClockwise } from "@phosphor-icons/react";
import { applyDocumentLocale, copy, type Locale } from "./locales";
import { createItem, loadPrototypeData, resetPrototypeData, resolveDuplicate, savePrototypeData, type OnboardingAnswers, type PrototypeData, type WardrobeItem } from "./prototype-data";
import { Card, EmptyState, PageHeader, PrimaryButton, SecondaryButton } from "./ui";

type Destination = "today" | "wardrobe" | "add" | "outfits" | "profile";
type Draft = Omit<WardrobeItem, "id" | "createdAt" | "archived">;
const destinations: Destination[] = ["today", "wardrobe", "add", "outfits", "profile"];
const navIcons = { today: CalendarBlank, wardrobe: CoatHanger, add: Plus, outfits: Sparkle, profile: UserCircle };
const blankDraft = (): Draft => ({ name: "", category: "חולצה", color: "", season: "כל השנה", style: "", quantity: 1 });
const detectedDraft = (): Draft => ({ name: "חולצת כותנה כחולה", category: "חולצה", color: "כחול", season: "כל השנה", style: "קז'ואל", quantity: 1 });
const he = (locale: Locale, hebrew: string, english: string) => locale === "he-IL" ? hebrew : english;
function LanguageSwitcher({ locale, setLocale }: { locale: Locale; setLocale: (v: Locale) => void }) { return <label className="language-switcher"><span>{copy[locale].switchLanguage}</span><select value={locale} onChange={(e) => setLocale(e.target.value as Locale)}><option value="he-IL">עברית</option><option value="en">English</option></select></label>; }
function BottomNavigation({ active, locale, onSelect }: { active: Destination; locale: Locale; onSelect: (d: Destination) => void }) { return <nav className="bottom-nav" aria-label={he(locale, "ניווט ראשי", "Primary navigation")}>{destinations.map((destination) => { const Icon = navIcons[destination]; return <button key={destination} className={`bottom-nav__item ${active === destination ? "is-active" : ""} ${destination === "add" ? "bottom-nav__item--add" : ""}`} type="button" aria-current={active === destination ? "page" : undefined} onClick={() => onSelect(destination)}><Icon aria-hidden="true" weight={destination === "add" ? "bold" : "regular"}/><span>{copy[locale].nav[destination]}</span></button>; })}</nav>; }

function NumericPicker({ value, setValue, min, max, unit, label }: { value: number; setValue: (n: number) => void; min: number; max: number; unit: string; label: string }) { return <div className="numeric-picker"><output aria-live="polite">{value} <small>{unit}</small></output><label>{label}<input type="range" min={min} max={max} value={value} onChange={(e) => setValue(Number(e.target.value))}/></label><div><SecondaryButton onClick={() => setValue(Math.max(min, value - 1))} aria-label="הפחתה">−</SecondaryButton><SecondaryButton onClick={() => setValue(Math.min(max, value + 1))} aria-label="הוספה">+</SecondaryButton></div></div>; }
function Onboarding({ data, update }: { data: PrototypeData; update: (next: PrototypeData) => void }) {
  const steps = ["welcome", "presentation", "height", "weight", "age", "goals", "style", "start"] as const; const [step, setStep] = useState(data.onboarding.step); const [answers, setAnswers] = useState<OnboardingAnswers>(data.onboarding.answers); const current = steps[step];
  const save = (complete = false, nextStep = step) => update({ ...data, onboarding: { step: nextStep, complete, answers } });
  const next = () => { const final = step === steps.length - 1; save(final, final ? step : step + 1); if (!final) setStep(step + 1); };
  const skip = () => { if (current === "weight") setAnswers((a) => ({ ...a, weightKg: undefined })); next(); };
  const choice = (key: "presentation" | "goals" | "style" | "start", options: string[], multi = false) => <div className="choice-list">{options.map((option) => { const selected = multi ? (answers[key] as string[] | undefined)?.includes(option) : answers[key] === option; return <button type="button" className={selected ? "choice is-selected" : "choice"} onClick={() => setAnswers((a) => ({ ...a, [key]: multi ? (selected ? ((a[key] as string[]) || []).filter((x) => x !== option) : [...((a[key] as string[]) || []), option]) : option }))} key={option}>{option}</button>; })}</div>;
  const titles = { welcome: ["ברוכים הבאים לארון שלך", "נבנה יחד ארון דיגיטלי פשוט, פריט אחד בכל פעם."], presentation: ["איך נוח לך לראות לוקים?", "נציג לוקים על קולב, שטוח או כהשראה בלבד."], height: ["מה הגובה שלך?", "אפשר לדלג — הנתון אופציונלי."], weight: ["מה המשקל שלך?", "אופציונלי לחלוטין, ואפשר לדלג."], age: ["מה הגיל שלך?", "אפשר לדלג — הנתון אופציונלי."], goals: ["מה חשוב לך מהארון?", "אפשר לבחור יותר מתשובה אחת."], style: ["איזה סגנון מרגיש לך נכון?", "אפשר לבחור יותר מתשובה אחת."], start: ["איך נתחיל?", "תמיד אפשר להוסיף עוד אחר כך."] }[current];
  return <main className="onboarding"><div className="onboarding__progress" aria-label={`שלב ${step + 1} מתוך ${steps.length}`}><span style={{ width: `${((step + 1) / steps.length) * 100}%` }}/></div><p className="eyebrow">שלב {step + 1} מתוך {steps.length}</p><h1>{titles[0]}</h1><p>{titles[1]}</p>{current === "presentation" && choice("presentation", ["על קולב", "לוק שטוח", "השראה מצולמת"])}{current === "height" && <NumericPicker value={answers.heightCm ?? 170} setValue={(heightCm) => setAnswers((a) => ({ ...a, heightCm }))} min={140} max={220} unit="ס״מ" label="גובה בין 140 ל־220 ס״מ"/>}{current === "weight" && <NumericPicker value={answers.weightKg ?? 65} setValue={(weightKg) => setAnswers((a) => ({ ...a, weightKg }))} min={25} max={350} unit="ק״ג" label="משקל בקילוגרמים"/>}{current === "age" && <><NumericPicker value={answers.age ?? 30} setValue={(age) => setAnswers((a) => ({ ...a, age }))} min={13} max={120} unit="שנים" label="גיל"/><p className="derived-year">שנת לידה משוערת: {new Date().getFullYear() - (answers.age ?? 30)}</p></>}{current === "goals" && choice("goals", ["להתלבש מהר", "לגלות שילובים", "לנצל מה שכבר יש"], true)}{current === "style" && choice("style", ["קלאסי", "נינוח", "נועז"], true)}{current === "start" && choice("start", ["צלמו את הלוק של היום", "בחרו תמונות", "דלגו לעת עתה"])}<div className="onboarding__actions">{step > 0 && <SecondaryButton onClick={() => { save(false, step - 1); setStep(step - 1); }}>חזרה</SecondaryButton>}<PrimaryButton onClick={next}>{step === steps.length - 1 ? "סיום" : "המשך"}<ArrowRight weight="bold"/></PrimaryButton>{["height", "weight", "age"].includes(current) && <button type="button" className="link-button" onClick={skip}>דלגו</button>}</div></main>;
}

function ItemForm({ initial, onSave, onCancel }: { initial?: WardrobeItem; onSave: (d: Draft) => void; onCancel: () => void }) { const [draft, setDraft] = useState<Draft>(initial ? { name: initial.name, category: initial.category, color: initial.color, season: initial.season, style: initial.style, quantity: initial.quantity, image: initial.image } : blankDraft()); return <form className="item-form" onSubmit={(e) => { e.preventDefault(); onSave(draft); }}><label>שם הפריט<input required value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })}/></label><label>קטגוריה<select value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })}>{["חולצה", "מכנסיים", "שמלה", "ז׳קט", "נעליים", "אביזר"].map((x) => <option key={x}>{x}</option>)}</select></label><label>צבע<input value={draft.color} onChange={(e) => setDraft({ ...draft, color: e.target.value })}/></label><label>עונה<input value={draft.season} onChange={(e) => setDraft({ ...draft, season: e.target.value })}/></label><label>סגנון<input value={draft.style} onChange={(e) => setDraft({ ...draft, style: e.target.value })}/></label><label>כמות<input type="number" min="1" value={draft.quantity} onChange={(e) => setDraft({ ...draft, quantity: Number(e.target.value) })}/></label><div className="form-actions"><SecondaryButton onClick={onCancel}>ביטול</SecondaryButton><PrimaryButton type="submit">שמירת תיקונים</PrimaryButton></div></form>; }
function ItemGrid({ items, open }: { items: WardrobeItem[]; open: (i: WardrobeItem) => void }) { return <div className="item-grid">{items.map((item) => <button type="button" className="item-tile" onClick={() => open(item)} key={item.id}>{item.image ? <img src={item.image} alt=""/> : <span className="item-tile__placeholder">{item.category}</span>}<strong>{item.name}</strong><small>{item.color || item.category} · {item.quantity}</small></button>)}</div>; }
function Today({ locale, items, go }: { locale: Locale; items: WardrobeItem[]; go: (d: Destination) => void }) { const recent = items.filter((item) => !item.archived).slice(-3).reverse(); if (!recent.length) return <main className="page"><PageHeader eyebrow={he(locale, "הארון שלך, בקצב שלך", "Your wardrobe, at your pace")} title={he(locale, "לא צריך לצלם את כל הארון היום.", "No need to photograph everything today.")}/><Card className="today-hero"><EmptyState title={he(locale, "מתחילים מפריט אחד", "Start with one item")} body={he(locale, "הארון גדל בהדרגה. אפשר להתחיל מלוק של היום או מפריט אחד.", "Your wardrobe grows gradually. Start with today's look or one item.")}><PrimaryButton onClick={() => go("add")}>צלמו את הלוק של היום</PrimaryButton></EmptyState></Card></main>; return <main className="page"><PageHeader eyebrow="היום" title={`יש בארון ${items.filter((x) => !x.archived).length} פריטים`}/><h2 className="section-title">נוספו לאחרונה</h2><ItemGrid items={recent} open={() => go("wardrobe")}/></main>; }
function Wardrobe({ data, update, go }: { data: PrototypeData; update: (d: PrototypeData) => void; go: (d: Destination) => void }) { const [selected, setSelected] = useState<WardrobeItem | null>(null); const active = data.items.filter((x) => !x.archived); const save = (draft: Draft) => { if (selected) update({ ...data, items: data.items.map((x) => x.id === selected.id ? { ...x, ...draft } : x) }); setSelected(null); }; if (selected) return <main className="page"><PageHeader title="עריכת פריט"/><ItemForm initial={selected} onSave={save} onCancel={() => setSelected(null)}/><div className="danger-actions"><SecondaryButton onClick={() => update({ ...data, items: data.items.map((x) => x.id === selected.id ? { ...x, archived: !x.archived } : x) })}>{selected.archived ? <><ArrowCounterClockwise/>שחזור</> : <><Archive/>ארכוב</>}</SecondaryButton><SecondaryButton onClick={() => { if (confirm("למחוק את הפריט לצמיתות?")) { update({ ...data, items: data.items.filter((x) => x.id !== selected.id) }); setSelected(null); } }}><Trash/>מחיקה</SecondaryButton></div></main>; return <main className="page"><PageHeader eyebrow="הארון" title="הפריטים שלך"><PrimaryButton onClick={() => go("add")}><Plus/>הוספת פריט</PrimaryButton></PageHeader>{active.length ? <ItemGrid items={active} open={setSelected}/> : <Card><EmptyState title="הארון עדיין ריק" body="צלמו או בחרו תמונה כדי להתחיל."><PrimaryButton onClick={() => go("add")}>הוספת פריט בצילום</PrimaryButton></EmptyState></Card>}<details className="archive-list"><summary>פריטים בארכיון ({data.items.length - active.length})</summary>{data.items.filter((x) => x.archived).map((item) => <button type="button" onClick={() => setSelected(item)} key={item.id}>{item.name}</button>)}</details></main>; }
function Add({ data, update, go }: { data: PrototypeData; update: (d: PrototypeData) => void; go: (d: Destination) => void }) { const [image, setImage] = useState<string>(); const [state, setState] = useState<"choose" | "processing" | "review" | "edit">("choose"); const [candidate, setCandidate] = useState<Draft>(detectedDraft()); const [duplicate, setDuplicate] = useState(false); const match = data.items.find((x) => !x.archived); const file = (e: ChangeEvent<HTMLInputElement>) => { const item = e.target.files?.[0]; if (item) { const reader = new FileReader(); reader.onload = () => { setImage(String(reader.result)); setCandidate({ ...detectedDraft(), image: String(reader.result) }); setState("processing"); }; reader.readAsDataURL(item); } }; const approve = () => match ? setDuplicate(true) : (update({ ...data, items: [...data.items, createItem(candidate)] }), go("wardrobe")); if (duplicate && match) return <main className="page"><PageHeader title="בדיקת כפילות מדומה"/><Card><p className="prototype-note">לוגיקת אבטיפוס בלבד — לא בוצע ניתוח דמיון אמיתי.</p><div className="duplicate-pair"><span>{candidate.name}</span><span>{match.name}</span></div>{[["same", "זה אותו פריט שכבר קיים"], ["additional", "יש לי פריט נוסף שנראה זהה"], ["different", "זה פריט אחר"]].map(([decision, label]) => <PrimaryButton key={decision} onClick={() => { update({ ...data, items: resolveDuplicate(data.items, createItem(candidate), decision as "same" | "additional" | "different", match.id) }); go("wardrobe"); }}>{label}</PrimaryButton>)}</Card></main>;
 if (state === "processing") return <main className="page"><PageHeader title="מעבדים את התמונה"/><Card className="processing-card">{image && <img className="image-preview" src={image} alt="התמונה שנבחרה"/>}<p className="prototype-note">עיבוד מדומה — זיהוי הפריט ייווצר לצורך בדיקת הזרימה.</p><PrimaryButton onClick={() => setState("review")}>הצגת הזיהוי המדומה</PrimaryButton><SecondaryButton onClick={() => setState("choose")}>מחיקת התמונה</SecondaryButton></Card></main>;
 if (state === "review" || state === "edit") return <main className="page"><PageHeader title="בדיקת זיהוי מדומה"/><Card>{image && <img className="image-preview" src={image} alt="התמונה שנבחרה"/>}<p className="prototype-note">זהו זיהוי מדומה לצורך בדיקת חוויית המשתמש.</p>{state === "review" ? <><div className="detected-tags" aria-label="פרטים שזוהו">{[candidate.name, candidate.category, candidate.color, candidate.season, candidate.style, `כמות ${candidate.quantity}`].map((tag) => <span key={tag}>{tag}</span>)}</div><SecondaryButton onClick={() => setState("edit")}>עריכת פרטים</SecondaryButton></> : <ItemForm initial={{ ...createItem(candidate) }} onSave={(draft) => { setCandidate(draft); setState("review"); }} onCancel={() => setState("review")}/>}<div className="form-actions"><SecondaryButton onClick={() => { setImage(undefined); setState("choose"); }}>דחייה ומחיקה</SecondaryButton><PrimaryButton onClick={approve}>אישור ושמירה בארון</PrimaryButton></div></Card></main>;
 return <main className="page"><PageHeader title="הוספת פריט"/><p>בחרו איך לצלם או להעלות תמונה. אפשר לצלם כמה פריטים יחד.</p><div className="add-options">{[[Camera, "צילום פריט"], [Camera, "צילום כמה פריטים יחד"], [ImageIcon, "בחירת תמונה מהגלריה"]].map(([Icon, label]) => <label className="add-option" key={String(label)}><Icon/><span>{label as string}</span><input type="file" accept="image/*" capture={label === "בחירת תמונה מהגלריה" ? undefined : "environment"} onChange={file}/></label>)}</div></main>; }
function Outfits({ data, update }: { data: PrototypeData; update: (d: PrototypeData) => void }) { const items = data.items.filter((x) => !x.archived); if (items.length < 2) return <main className="page"><PageHeader title="לוקים"/><Card><EmptyState title="כדאי להוסיף עוד פריטים" body="כשיהיו לפחות שני פריטים, נציג כאן שילובים מקומיים לדוגמה."/></Card></main>; return <main className="page"><PageHeader title="לוקים לדוגמה"/>{[0, 1].map((n) => { const id = `outfit-${n}`; const favorite = data.favorites.includes(id); return <Card className="outfit-card" key={id}><div>{items.slice(n, n + 2).map((x) => <span key={x.id}>{x.name}</span>)}</div><SecondaryButton onClick={() => update({ ...data, favorites: favorite ? data.favorites.filter((x) => x !== id) : [...data.favorites, id] })}>♥ {favorite ? "נשמר" : "שמירה"}</SecondaryButton></Card>; })}</main>; }
const chips = (values: string[] | undefined, fallback: string) => values?.length ? values.map((value) => <span className="profile-chip" key={value}>{value}</span>) : <span className="profile-empty">{fallback}</span>;
function Profile({ data, update, locale, setLocale, restart }: { data: PrototypeData; update: (d: PrototypeData) => void; locale: Locale; setLocale: (l: Locale) => void; restart: () => void }) { const answers = data.onboarding.answers; return <main className="page"><PageHeader title="פרופיל"/><Card className="profile-card"><h2>הפרטים שלי</h2><dl className="profile-details"><div><dt>סוגי לוקים מועדפים</dt><dd>{answers.presentation || "טרם נבחר"}</dd></div>{answers.heightCm && <div><dt>גובה</dt><dd>{answers.heightCm} ס״מ</dd></div>}{answers.age && <div><dt>גיל</dt><dd>{answers.age}</dd></div>}{answers.weightKg && <div><dt>משקל</dt><dd>{answers.weightKg} ק״ג</dd></div>}</dl></Card><Card className="profile-card"><h2>המטרות שלי</h2><div className="profile-chips">{chips(answers.goals, "טרם נבחרו מטרות")}</div><h2>הסגנון שלי</h2><div className="profile-chips">{chips(answers.style, "טרם נבחר סגנון")}</div></Card><Card className="profile-card"><LanguageSwitcher locale={locale} setLocale={setLocale}/><SecondaryButton onClick={restart}>התחלה מחדש של ההיכרות</SecondaryButton></Card><Card className="profile-card"><h2>פרטיות</h2><p>כעת הנתונים נשמרים רק בדפדפן במכשיר הזה. אין עדיין חשבון, ענן או שיתוף מידע.</p><SecondaryButton onClick={() => { if (confirm("למחוק את כל נתוני האבטיפוס?")) { resetPrototypeData(); update(loadPrototypeData()); } }}>מחיקת נתוני האבטיפוס</SecondaryButton></Card></main>; }
export function AppShell() { const [data, setData] = useState<PrototypeData>(() => loadPrototypeData()); const [locale, setLocale] = useState<Locale>(() => (localStorage.getItem("wardrobe-locale") as Locale) || "he-IL"); const [active, setActive] = useState<Destination>("today"); useEffect(() => { applyDocumentLocale(locale); localStorage.setItem("wardrobe-locale", locale); }, [locale]); const update = (next: PrototypeData) => { setData(next); savePrototypeData(next); }; if (!data.onboarding.complete) return <div className="app-shell"><Onboarding data={data} update={update}/></div>; const props = { data, update }; const content = active === "today" ? <Today locale={locale} items={data.items} go={setActive}/> : active === "wardrobe" ? <Wardrobe {...props} go={setActive}/> : active === "add" ? <Add {...props} go={setActive}/> : active === "outfits" ? <Outfits {...props}/> : <Profile {...props} locale={locale} setLocale={setLocale} restart={() => update({ ...data, onboarding: { ...data.onboarding, complete: false, step: 0 } })}/>; return <div className="app-shell"><div className="app-shell__top"><LanguageSwitcher locale={locale} setLocale={setLocale}/></div>{content}<BottomNavigation active={active} locale={locale} onSelect={setActive}/></div>; }
